### ISSUE TITLE
Student exercises

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/cornerstone-2015-unix-FUNdamentals#2]
In Rochelle's materials, these are currently questions placed at the end of each document. Is there a way we could make this more interactive? E.g. @davclark does pytest also work for bash scripts?

**Comment by davclark** [comment]
First - ensure that everything will run on git bash. Jack can lend you a computer with windows.

Second, the easiest way is to have a well-specified "test" that folks can run by hand. An easy approach would be `diff` with a desired result (which you provide as a file in the repo) and a computed result. (`diff` is available in git bash.) You could even write a script that does a diff or similar. Indeed, you could even use pytest... All pytest does is run a bunch of functions and assert that things are true. But we aren't going to rely on python. So, if you want to use unit-tests, I've liked `testthat` in R.

But I think the manual approach would be nice. I.e., a script called `challenge1.sh` that is simply:

```
diff target_data.txt computed_data.txt
```

Or you could even have a script like this:

```
diff target_data.txt -
```

To test that folks grok piping (`-` will make diff compare to standard input).
