### ISSUE TITLE
Who can make mornings Sept 7-9

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/cornerstone-2015-unix-FUNdamentals#6]
Sound off here!

@davclark would prefer to do the 7th and / or 9th. Tuesdays are busy.

**Comment by rdhyee** [comment]
I'm out of town during the Sept 7-9 period.

**Comment by juanshishido** [comment]
I'm available before 10:30 MW. Tuesday only available between 11 and 12.

**Comment by davclark** [comment]
I didn't realize I'd get other folks chiming in on this issue! To clarify, we are teaching in SF at the Cornerstone offices. So, if you have a short window, you likely can't go there.

We might also have one or two people providing support by hanging out online, though. So, folks can let me know if they'd be available for that!

**Comment by deniederhut** [comment]
@deniederhut will likely be free Tue 8, less likely Mon 7, not at all Wed 9

**Comment by deniederhut** [comment]
Closing, because dates have moved.
